server:
  port: 0
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

spring:
  application:
    name: asset-service
  config:
    import:
      - optional:configserver:http://localhost:8888
      - logging.yml
      - monitoring.yml
      - core-domain.yml
      - storage-db-core.yml
  web.resources.add-mappings: false

  kafka:
      bootstrap-servers: localhost:9092
      consumer:
          auto-offset-reset: earliest

---
spring.config.activate.on-profile: local

server:
  port: 9040

---
spring.config.activate.on-profile: local-dev
