server:
  port: 0
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

spring:
  application:
    name: asset-service
  config:
    import:
      - optional:configserver:http://localhost:8888
      - core-domain.yml
  web.resources.add-mappings: false

---
spring.config.activate.on-profile: local



---
spring.config.activate.on-profile: local-dev